version: "2"

services:
    core:
        build: 
            context: ./backend
            target: dev
        working_dir: /backend
        volumes:
          - ./backend:/backend
        command: npm run start:dev
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - "3001:3000"
        environment:
            NODE_ENV: development
            DEBUG: nodejs-docker-express:*

    postgres:
        image: postgres
        volumes:
            - psql-data:/var/lib/postgresql/data
            - ./ops:/ops
        environment:
            - POSTGRES_PASSWORD=zekjijfznfr32
            - POSTGRES_USER=core
            - POSTGRES_DB=todolisttestdb
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d todolisttestdb -U core"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    psql-data:
        driver: local
