name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deployment:

    runs-on: ubuntu-latest
    environment: PROD
    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        host: 217.160.34.121
        username: root
        password: CE%dzFN%f1
        port: 22
        rm: true
        source: "./backend"
        target: "/var/www/todolist"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: ls
