name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deployment:

    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        rm: true
        source: "./backend"
        target: "/var/www/todolist"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cp /var/.env /var/www/todolist/backend
          cd /var/www/todolist/backend
          node -v
          npm install
          npm run swagger
          pm2 restart backendServer
